# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['14.x', '15.x']

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node_version }}
          
      - name: Download, build and test
        run: |
          yarn install
          yarn run g:build
          yarn run g:test

